version: "3.8"
services:

  wordpress:
    build: ./requirements/wordpress/
    image: wordpress:ppp
    container_name: wordpressAAA
    restart: on-failure
    ports:
      - 444:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html

  db:
    build: ./requirements/mariadb/
    image: maria:ppp
    container_name: MARIAAAA
    restart: on-failure
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:


# wp-config.php