version: "3.8"

services:

  nginx:
    container_name: nginx
    image: nginx:v1.0.0
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - WordPress:/var/www/html
    restart: on-failure
    networks:
      - inception-network

  wordpress:
    container_name: wordpress
    image: wordpress:v1.0.0
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - WordPress:/var/www/html
    restart: on-failure
    networks:
      - inception-network
    env_file:
      - ./.env

  mariadb:
    container_name: mariadb
    image: mariadb:v1.0.0
    build: ./requirements/mariadb
    volumes:
      - DB:/var/lib/mysql
    restart: on-failure
    networks:
      - inception-network
    env_file:
      - ./.env

volumes:     #/home/idouni/data/
  DB:
  WordPress:    

networks:
  inception-network:
    name : inception-network
