version: '3.8'
services:
  nginx:
    container_name: nginx
    build: ./srcs/requirements/nginx
    ports:
      - 443:443
    volumes:
      - wp:/var/www/html
    restart: on-failure

    networks:
      - wordpress-network
  
  wordpress:
    container_name: wordpress
    build: ./srcs/requirements/wordpress
    volumes:
      - wp:/var/www/html
    restart: on-failure

    networks:
      - wordpress-network

volumes:
  wp:

networks:
  wordpress-network:
    driver: bridge
