version: "3.8"

services:

  nginx:
    container_name: nginx
    build: ./srcs/requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - /Users/idouni/Desktop/Inception/HTML:/var/www/html #WordPress:-
    restart: on-failure
    networks:
      - inception-network

  wordpress:
    container_name: wordpress
    build: ./srcs/requirements/wordpress
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    volumes:
      - /Users/idouni/Desktop/Inception/HTML:/var/www/html #WordPress:-
    restart: on-failure
    networks:
      - inception-network

    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  mariadb:
    container_name: mariadb
    build: ./srcs/requirements/mariadb
    ports:
      - "3306:3306"
    volumes:
      - DB:/var/lib/mysql
    restart: on-failure
    networks:
      - inception-network

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

volumes:
  DB:
  WordPress:

networks:
  inception-network:
    name : inception-network
