version: "3.8"

services:

  nginx:
    container_name: nginx
    build: ./srcs/requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - WordPress:/var/www/html
    restart: on-failure
    networks:
      - inception-network

  wordpress:
    container_name: wordpress
    build: ./srcs/requirements/wordpress
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    volumes:
      - WordPress:/var/www/html
    restart: on-failure
    networks:
      - inception-network
    env_file:
      - ./.env

  mariadb:
    container_name: mariadb
    build: ./srcs/requirements/mariadb
    ports:
      - "3306:3306"
    volumes:
      - DB:/var/lib/mysql #DB:
    restart: on-failure
    networks:
      - inception-network
    env_file:
      - ./.env

volumes:     #/home/idouni/data/
  DB:
  WordPress:    

networks:
  inception-network:
    name : inception-network
