version: "3.8"

services:

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:v1.0 
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - WordPress:/var/www/html
    restart: on-failure
    networks:
      - inception-network

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:v1.0 
    depends_on:
      - mariadb
    volumes:
      - WordPress:/var/www/html
    restart: on-failure
    networks:
      - inception-network
    env_file:
      - ./.env

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:v1.0 
    volumes:
      - DB:/var/lib/mysql
    restart: on-failure
    networks:
      - inception-network
    env_file:
      - ./.env

volumes:
  DB:
    name : DB
    driver: local
    driver_opts:
      o: bind
      type: none
      device:  /home/idouni/data/DB

  WordPress:
    name : WordPress
    driver: local
    driver_opts:
      o: bind
      type: none
      device:  /home/idouni/data/WordPress

networks:
  inception-network:
    name : inception-network
