FROM debian:12

RUN apt-get update -y\
 && apt-get upgrade -y\
 && apt-get install php-fpm -y\
 && apt-get install php-mysql -y\
 && apt-get install curl -y

# COPY script.sh .

# RUN ["bash", "script.sh"]
